title: Emerald Rook
description: "Rare by design"
url: "https://abdullahharithworks.github.io"
baseurl: ""

markdown: kramdown

# Company-specific variables
company_name: "Emerald Rook"
company_tagline: "Rare by design"
company_email: "hello@emeraldrook.com"
company_github: "https://github.com/emeraldrook"
company_linkedin: "https://linkedin.com/company/emeraldrook"
